/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TariffsImport } from './routes/tariffs'
import { Route as ServicesImport } from './routes/services'
import { Route as RevenueImport } from './routes/revenue'
import { Route as OrdersImport } from './routes/orders'
import { Route as IndexImport } from './routes/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthEmailImport } from './routes/auth/$email'

// Create/Update Routes

const TariffsRoute = TariffsImport.update({
  id: '/tariffs',
  path: '/tariffs',
  getParentRoute: () => rootRoute,
} as any)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const RevenueRoute = RevenueImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRoute,
} as any)

const OrdersRoute = OrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthEmailRoute = AuthEmailImport.update({
  id: '/auth/$email',
  path: '/auth/$email',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/tariffs': {
      id: '/tariffs'
      path: '/tariffs'
      fullPath: '/tariffs'
      preLoaderRoute: typeof TariffsImport
      parentRoute: typeof rootRoute
    }
    '/auth/$email': {
      id: '/auth/$email'
      path: '/auth/$email'
      fullPath: '/auth/$email'
      preLoaderRoute: typeof AuthEmailImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/services': typeof ServicesRoute
  '/tariffs': typeof TariffsRoute
  '/auth/$email': typeof AuthEmailRoute
  '/auth': typeof AuthIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/services': typeof ServicesRoute
  '/tariffs': typeof TariffsRoute
  '/auth/$email': typeof AuthEmailRoute
  '/auth': typeof AuthIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/orders': typeof OrdersRoute
  '/revenue': typeof RevenueRoute
  '/services': typeof ServicesRoute
  '/tariffs': typeof TariffsRoute
  '/auth/$email': typeof AuthEmailRoute
  '/auth/': typeof AuthIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/orders'
    | '/revenue'
    | '/services'
    | '/tariffs'
    | '/auth/$email'
    | '/auth'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/orders'
    | '/revenue'
    | '/services'
    | '/tariffs'
    | '/auth/$email'
    | '/auth'
  id:
    | '__root__'
    | '/'
    | '/orders'
    | '/revenue'
    | '/services'
    | '/tariffs'
    | '/auth/$email'
    | '/auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrdersRoute: typeof OrdersRoute
  RevenueRoute: typeof RevenueRoute
  ServicesRoute: typeof ServicesRoute
  TariffsRoute: typeof TariffsRoute
  AuthEmailRoute: typeof AuthEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrdersRoute: OrdersRoute,
  RevenueRoute: RevenueRoute,
  ServicesRoute: ServicesRoute,
  TariffsRoute: TariffsRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/orders",
        "/revenue",
        "/services",
        "/tariffs",
        "/auth/$email",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/orders": {
      "filePath": "orders.tsx"
    },
    "/revenue": {
      "filePath": "revenue.tsx"
    },
    "/services": {
      "filePath": "services.tsx"
    },
    "/tariffs": {
      "filePath": "tariffs.tsx"
    },
    "/auth/$email": {
      "filePath": "auth/$email.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
